openapi: 3.0.3
info:
  title: 租赁管理系统 - 简化附件选择 API
  description: |
    租赁订单附件管理API规范,支持配套附件(手柄、镜头支架)和库存附件(手机支架、三脚架)的简化选择。
    
    **变更说明**:
    - 添加 `includes_handle` 和 `includes_lens_mount` 布尔字段
    - `accessories` 字段现在只包含库存附件(手机支架、三脚架)
    - 新增 `all_accessories` 字段返回完整附件信息(用于打印和甘特图)
  version: 2.0.0
  contact:
    name: 开发团队
servers:
  - url: http://localhost:5000/api
    description: 本地开发环境
  - url: https://api.inventory.example.com/api
    description: 生产环境

tags:
  - name: Rentals
    description: 租赁订单管理
  - name: Gantt
    description: 甘特图数据
  - name: Printing
    description: 打印服务

paths:
  /rentals:
    post:
      tags:
        - Rentals
      summary: 创建租赁订单
      description: |
        创建新的租赁订单,支持选择配套附件和库存附件。
        
        **配套附件** (通过布尔字段):
        - `includes_handle`: 是否包含手柄
        - `includes_lens_mount`: 是否包含镜头支架
        
        **库存附件** (通过ID数组):
        - `accessory_ids`: 手机支架和三脚架的设备ID列表
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRentalRequest'
            examples:
              完整订单:
                value:
                  device_id: 123
                  start_date: "2026-01-05"
                  end_date: "2026-01-10"
                  customer_name: "张三"
                  customer_phone: "13800138000"
                  destination: "北京市朝阳区"
                  xianyu_order_no: "XY202601050001"
                  order_amount: 500.00
                  includes_handle: true
                  includes_lens_mount: false
                  accessory_ids: [45, 67]
              仅配套附件:
                value:
                  device_id: 123
                  start_date: "2026-01-05"
                  end_date: "2026-01-10"
                  customer_name: "李四"
                  customer_phone: "13900139000"
                  includes_handle: true
                  includes_lens_mount: true
                  accessory_ids: []
      responses:
        '201':
          description: 订单创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 设备或附件档期冲突
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResponse'
    
    get:
      tags:
        - Rentals
      summary: 获取租赁订单列表
      description: 分页获取租赁订单列表,支持按状态、日期、附件类型筛选
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: status
          in: query
          description: 订单状态筛选
          schema:
            type: string
            enum: [not_shipped, scheduled_for_shipping, shipped, returned, completed, cancelled]
        - name: start_date
          in: query
          description: 筛选开始日期(YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: 筛选结束日期(YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: includes_handle
          in: query
          description: 筛选包含手柄的订单
          schema:
            type: boolean
        - name: includes_lens_mount
          in: query
          description: 筛选包含镜头支架的订单
          schema:
            type: boolean
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalListResponse'
  
  /rentals/{rental_id}:
    get:
      tags:
        - Rentals
      summary: 获取订单详情
      description: 获取单个租赁订单的完整信息,包括所有附件
      parameters:
        - name: rental_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalDetailResponse'
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    put:
      tags:
        - Rentals
      summary: 更新租赁订单
      description: 更新租赁订单信息,包括附件配置
      parameters:
        - name: rental_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRentalRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    delete:
      tags:
        - Rentals
      summary: 删除租赁订单
      description: 删除租赁订单及其关联的附件订单
      parameters:
        - name: rental_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 删除成功
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /gantt/data:
    get:
      tags:
        - Gantt
      summary: 获取甘特图数据
      description: 获取指定时间范围内的租赁订单数据,用于甘特图渲染
      parameters:
        - name: start_date
          in: query
          required: true
          description: 查询开始日期(YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: true
          description: 查询结束日期(YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: include_accessories
          in: query
          description: 是否包含附件信息
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GanttDataResponse'
  
  /shipping-batch/print-waybills:
    post:
      tags:
        - Printing
      summary: 批量打印面单
      description: 批量打印顺丰面单(附件信息会包含在备注或附加信息中)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rental_ids
              properties:
                rental_ids:
                  type: array
                  items:
                    type: integer
                  description: 需要打印面单的订单ID列表
                  example: [1001, 1002, 1003]
      responses:
        '200':
          description: 打印任务创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  print_job_ids:
                    type: array
                    items:
                      type: string
  
  /shipping-batch/generate-packing-slip:
    post:
      tags:
        - Printing
      summary: 生成发货单
      description: 生成发货单图像,包含完整的附件清单(配套附件和库存附件)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rental_id
              properties:
                rental_id:
                  type: integer
                  description: 租赁订单ID
                  example: 1001
      responses:
        '200':
          description: 发货单生成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  image_url:
                    type: string
                    format: uri
                    description: 发货单图像URL
                  image_base64:
                    type: string
                    format: byte
                    description: 发货单图像Base64编码

components:
  schemas:
    CreateRentalRequest:
      type: object
      required:
        - device_id
        - start_date
        - end_date
        - customer_name
      properties:
        device_id:
          type: integer
          description: 主设备ID
          example: 123
        start_date:
          type: string
          format: date
          description: 租赁开始日期
          example: "2026-01-05"
        end_date:
          type: string
          format: date
          description: 租赁结束日期
          example: "2026-01-10"
        customer_name:
          type: string
          maxLength: 100
          description: 客户姓名
          example: "张三"
        customer_phone:
          type: string
          maxLength: 20
          description: 客户电话
          example: "13800138000"
        destination:
          type: string
          maxLength: 100
          description: 目的地地址
          example: "北京市朝阳区"
        xianyu_order_no:
          type: string
          maxLength: 50
          description: 闲鱼订单号
          example: "XY202601050001"
        order_amount:
          type: number
          format: decimal
          description: 订单金额
          example: 500.00
        buyer_id:
          type: string
          maxLength: 100
          description: 买家ID
        includes_handle:
          type: boolean
          default: false
          description: 是否包含配套手柄
          example: true
        includes_lens_mount:
          type: boolean
          default: false
          description: 是否包含配套镜头支架
          example: false
        accessory_ids:
          type: array
          items:
            type: integer
          description: 库存附件设备ID列表(手机支架、三脚架等)
          example: [45, 67]
    
    UpdateRentalRequest:
      type: object
      properties:
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        customer_name:
          type: string
        customer_phone:
          type: string
        destination:
          type: string
        status:
          type: string
          enum: [not_shipped, scheduled_for_shipping, shipped, returned, completed, cancelled]
        includes_handle:
          type: boolean
          description: 更新手柄配置
        includes_lens_mount:
          type: boolean
          description: 更新镜头支架配置
        accessory_ids:
          type: array
          items:
            type: integer
          description: 更新库存附件列表
    
    RentalResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1001
        device_id:
          type: integer
          example: 123
        device_name:
          type: string
          example: "X200U-001"
        device_model:
          type: string
          example: "x200u"
        start_date:
          type: string
          format: date
          example: "2026-01-05"
        end_date:
          type: string
          format: date
          example: "2026-01-10"
        customer_name:
          type: string
          example: "张三"
        customer_phone:
          type: string
          example: "13800138000"
        status:
          type: string
          example: "not_shipped"
        includes_handle:
          type: boolean
          example: true
        includes_lens_mount:
          type: boolean
          example: false
        accessories:
          type: array
          description: 库存附件列表(不包含配套附件)
          items:
            $ref: '#/components/schemas/AccessoryInfo'
    
    RentalDetailResponse:
      allOf:
        - $ref: '#/components/schemas/RentalResponse'
        - type: object
          properties:
            all_accessories:
              type: array
              description: 完整附件列表(包含配套附件和库存附件)
              items:
                $ref: '#/components/schemas/FullAccessoryInfo'
    
    AccessoryInfo:
      type: object
      properties:
        id:
          type: integer
          description: 附件设备ID
          example: 45
        rental_id:
          type: integer
          description: 附件对应的租赁记录ID
          example: 1002
        name:
          type: string
          description: 附件名称
          example: "手机支架-P01"
        model:
          type: string
          example: "standard"
        serial_number:
          type: string
          example: "P01-20240501"
        type:
          type: string
          enum: [phone_holder, tripod, handle, lens_mount, other]
          description: 附件类型
          example: "phone_holder"
    
    FullAccessoryInfo:
      type: object
      properties:
        id:
          type: integer
          description: 附件设备ID(配套附件无此字段)
          example: 45
        name:
          type: string
          description: 附件名称
          example: "手柄"
        serial_number:
          type: string
          description: 附件序列号(配套附件无此字段)
          example: "P01-20240501"
        type:
          type: string
          enum: [phone_holder, tripod, handle, lens_mount]
          description: 附件类型
          example: "handle"
        is_bundled:
          type: boolean
          description: 是否为配套附件
          example: true
    
    RentalListResponse:
      type: object
      properties:
        total:
          type: integer
          description: 总记录数
          example: 150
        page:
          type: integer
          description: 当前页码
          example: 1
        per_page:
          type: integer
          description: 每页记录数
          example: 20
        items:
          type: array
          items:
            $ref: '#/components/schemas/RentalResponse'
    
    GanttDataResponse:
      type: object
      properties:
        devices:
          type: array
          description: 设备列表(甘特图行)
          items:
            type: object
            properties:
              device_id:
                type: integer
              device_name:
                type: string
              device_model:
                type: string
        rentals:
          type: array
          description: 租赁记录(甘特图条)
          items:
            type: object
            properties:
              id:
                type: integer
              device_id:
                type: integer
              customer_name:
                type: string
              start_date:
                type: string
                format: date
              end_date:
                type: string
                format: date
              status:
                type: string
              accessories:
                type: array
                description: 附件信息(含配套附件和库存附件)
                items:
                  $ref: '#/components/schemas/FullAccessoryInfo'
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误消息
          example: "设备ID 123 不存在"
        code:
          type: string
          description: 错误代码
          example: "DEVICE_NOT_FOUND"
    
    ConflictResponse:
      type: object
      properties:
        error:
          type: string
          description: 冲突描述
          example: "附件 手机支架-P01 在此时间段已被预订"
        conflicts:
          type: array
          items:
            type: object
            properties:
              device_id:
                type: integer
              device_name:
                type: string
              conflicting_rental_id:
                type: integer
              conflict_start_date:
                type: string
                format: date
              conflict_end_date:
                type: string
                format: date
