openapi: 3.0.3
info:
  title: 设备验货系统 API
  description: 验货记录管理、检查清单生成、验货记录查询和编辑的 RESTful API
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:5002/api
    description: 本地开发环境
  - url: https://api.example.com/api
    description: 生产环境

tags:
  - name: Inspection
    description: 验货记录相关操作
  - name: Rental
    description: 租赁记录查询（用于验货）

paths:
  # ==================== 验货流程 ====================
  
  /rentals/by-device/{device_id}/latest:
    get:
      summary: 根据设备编号查询最近的租赁记录
      description: 查询指定设备在今天之前的最近一条租赁记录，用于验货时显示租赁信息和生成检查清单
      tags:
        - Rental
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
          description: 设备编号（纯数字）
          example: "2001"
      responses:
        '200':
          description: 成功返回租赁记录
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/RentalDetail'
        '404':
          description: 未找到该设备的租赁记录
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "未找到该设备的租赁记录"
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "设备编号格式错误"

  /inspections:
    post:
      summary: 创建验货记录
      description: 提交验货结果，创建新的验货记录和检查项
      tags:
        - Inspection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInspectionRequest'
      responses:
        '201':
          description: 验货记录创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/InspectionRecord'
        '400':
          description: 请求参数错误或验证失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "租赁记录ID不能为空"
        '404':
          description: 租赁记录不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "租赁记录不存在"

    get:
      summary: 查询验货记录列表
      description: 获取验货记录列表，支持按设备名称和验货状态筛选，按时间倒序排列
      tags:
        - Inspection
      parameters:
        - name: device_name
          in: query
          required: false
          schema:
            type: string
          description: 设备名称/编号（模糊匹配）
          example: "2001"
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [normal, abnormal, all]
          description: 验货状态筛选
          example: "normal"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: 页码（从 1 开始）
          example: 1
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: 每页记录数
          example: 20
      responses:
        '200':
          description: 成功返回验货记录列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/InspectionRecordSummary'
                      total:
                        type: integer
                        description: 总记录数
                        example: 50
                      page:
                        type: integer
                        description: 当前页码
                        example: 1
                      per_page:
                        type: integer
                        description: 每页记录数
                        example: 20
                      pages:
                        type: integer
                        description: 总页数
                        example: 3
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /inspections/{inspection_id}:
    get:
      summary: 查询单个验货记录详情
      description: 获取指定验货记录的完整信息，包括所有检查项
      tags:
        - Inspection
      parameters:
        - name: inspection_id
          in: path
          required: true
          schema:
            type: integer
          description: 验货记录ID
          example: 1
      responses:
        '200':
          description: 成功返回验货记录详情
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/InspectionRecord'
        '404':
          description: 验货记录不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "验货记录不存在"

    put:
      summary: 更新验货记录
      description: 编辑已有的验货记录，修改检查项的勾选状态
      tags:
        - Inspection
      parameters:
        - name: inspection_id
          in: path
          required: true
          schema:
            type: integer
          description: 验货记录ID
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInspectionRequest'
      responses:
        '200':
          description: 验货记录更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/InspectionRecord'
        '400':
          description: 请求参数错误或验证失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 验货记录不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "验货记录不存在"

# ==================== 数据模型 ====================

components:
  schemas:
    # 租赁记录详情（用于验货）
    RentalDetail:
      type: object
      properties:
        id:
          type: integer
          description: 租赁记录ID
          example: 123
        device_id:
          type: integer
          description: 设备ID
          example: 2001
        device_name:
          type: string
          description: 设备名称/编号
          example: "2001"
        device_model:
          type: string
          description: 设备型号
          example: "iPhone 14 Pro"
        customer_name:
          type: string
          description: 客户姓名
          example: "张三"
        customer_phone:
          type: string
          description: 客户电话
          example: "13800138000"
        includes_handle:
          type: boolean
          description: 是否包含手柄
          example: true
        includes_lens_mount:
          type: boolean
          description: 是否包含镜头支架
          example: true
        photo_transfer:
          type: boolean
          description: 是否包含代传照片服务
          example: false
        accessories:
          type: array
          description: 个性化附件列表
          items:
            type: object
            properties:
              id:
                type: integer
                example: 46
              name:
                type: string
                example: "手机支架-P01"
              is_bundled:
                type: boolean
                example: false
        checklist:
          type: array
          description: 动态生成的检查清单（仅包含检查项名称）
          items:
            type: string
          example:
            - "手机,镜头无严重磕碰"
            - "摄像头各焦段无白色十字"
            - "镜头镜片清晰,无雾无破裂"
            - "镜头拆装顺滑"
            - "充电头和充电线"
            - "手柄"
            - "镜头支架"
    
    # 创建验货记录请求
    CreateInspectionRequest:
      type: object
      required:
        - rental_id
        - device_id
        - check_items
      properties:
        rental_id:
          type: integer
          description: 租赁记录ID
          example: 123
        device_id:
          type: integer
          description: 设备ID
          example: 2001
        inspector_user_id:
          type: integer
          nullable: true
          description: 验货人员ID（可选）
          example: null
        check_items:
          type: array
          description: 检查项列表
          items:
            type: object
            required:
              - item_name
              - is_checked
              - item_order
            properties:
              item_name:
                type: string
                description: 检查项名称
                example: "手机,镜头无严重磕碰"
              is_checked:
                type: boolean
                description: 是否勾选
                example: true
              item_order:
                type: integer
                description: 显示顺序
                example: 0
    
    # 更新验货记录请求
    UpdateInspectionRequest:
      type: object
      required:
        - check_items
      properties:
        check_items:
          type: array
          description: 更新后的检查项列表（只需包含 id 和 is_checked）
          items:
            type: object
            required:
              - id
              - is_checked
            properties:
              id:
                type: integer
                description: 检查项ID
                example: 1
              is_checked:
                type: boolean
                description: 是否勾选
                example: false
    
    # 验货记录完整信息
    InspectionRecord:
      type: object
      properties:
        id:
          type: integer
          description: 验货记录ID
          example: 1
        rental_id:
          type: integer
          description: 租赁记录ID
          example: 123
        device_id:
          type: integer
          description: 设备ID
          example: 2001
        device_name:
          type: string
          description: 设备名称/编号
          example: "2001"
        customer_name:
          type: string
          description: 客户姓名
          example: "张三"
        status:
          type: string
          enum: [normal, abnormal]
          description: 验货状态（normal=验机正常, abnormal=验机异常）
          example: "normal"
        inspector_user_id:
          type: integer
          nullable: true
          description: 验货人员ID
          example: null
        created_at:
          type: string
          format: date-time
          description: 创建时间
          example: "2026-01-04T14:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: 最后修改时间
          example: "2026-01-04T14:30:00Z"
        check_items:
          type: array
          description: 检查项列表
          items:
            $ref: '#/components/schemas/CheckItem'
    
    # 验货记录摘要信息（用于列表展示）
    InspectionRecordSummary:
      type: object
      properties:
        id:
          type: integer
          description: 验货记录ID
          example: 1
        rental_id:
          type: integer
          description: 租赁记录ID
          example: 123
        device_id:
          type: integer
          description: 设备ID
          example: 2001
        device_name:
          type: string
          description: 设备名称/编号
          example: "2001"
        device_model:
          type: string
          description: 设备型号
          example: "iPhone 14 Pro"
        customer_name:
          type: string
          description: 客户姓名
          example: "张三"
        status:
          type: string
          enum: [normal, abnormal]
          description: 验货状态
          example: "normal"
        created_at:
          type: string
          format: date-time
          description: 创建时间
          example: "2026-01-04T14:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: 最后修改时间
          example: "2026-01-04T14:30:00Z"
    
    # 验货检查项
    CheckItem:
      type: object
      properties:
        id:
          type: integer
          description: 检查项ID
          example: 1
        inspection_record_id:
          type: integer
          description: 所属验货记录ID
          example: 1
        item_name:
          type: string
          description: 检查项名称
          example: "手机,镜头无严重磕碰"
        is_checked:
          type: boolean
          description: 是否已勾选
          example: true
        item_order:
          type: integer
          description: 显示顺序
          example: 0
    
    # 错误响应
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: 错误信息
          example: "参数验证失败"
