"""Independent platform-administrator identity contracts and services."""

from .audit import (
    SqlAlchemyPlatformLoginAuditRecorder,
    SqlAlchemyPlatformStepUpAuditRecorder,
)
from .cli import PlatformAdminCliApplication

from .factor_service import (
    IssuedRecoveryCodeBatch,
    PlatformCurrentFactorService,
    PlatformFactorRejected,
    PlatformRecoveryCodeService,
    PlatformTotpService,
    VerifiedPlatformFactor,
    activate_admin_if_ready,
)
from .host_service import (
    PlatformAdminDisableResult,
    PlatformAdminHostService,
    PlatformHostOperationRejected,
)
from .passwords import (
    PlatformPasswordError,
    PlatformPasswordHash,
    PlatformPasswordHasher,
)
from .login_service import (
    PlatformAdminLoginService,
    PlatformLoginAuditEvent,
    PlatformLoginAuditRecorder,
    PlatformLoginPolicy,
    PlatformLoginRejected,
)
from .rate_limit import (
    PlatformAdminRateLimiter,
    PlatformAuthRateLimiter,
    PlatformRateLimitBlocked,
    PlatformRateLimitPolicy,
    PlatformRateLimitRule,
    PlatformRateLimitSubjects,
)
from .session_service import (
    IssuedPlatformAdminSession,
    PlatformAdminSessionService,
    PlatformAuthSession,
    PlatformCsrfAuthenticationError,
    PlatformRevokeAllResult,
    PlatformSessionAuthenticationError,
    PlatformSessionIssueError,
    PlatformSessionTargetUnavailable,
)
from .step_up_service import (
    PlatformAdminStepUpService,
    PlatformStepUpAuditEvent,
    PlatformStepUpAuditRecorder,
    PlatformStepUpRejected,
)
from .setup_service import (
    ConsumedSetupAuthority,
    IssuedSetupChallenge,
    PlatformAdminSetupService,
    SetupChallengeResult,
)
from .tokens import (
    PLATFORM_TOKEN_DIGEST_BYTES,
    PLATFORM_TOKEN_ENTROPY_BITS,
    PLATFORM_TOKEN_ENTROPY_BYTES,
    IssuedPlatformToken,
    PlatformCredentialError,
    digest_platform_csrf_token,
    digest_platform_session_token,
    digest_recovery_code,
    digest_setup_token,
    issue_platform_csrf_token,
    issue_platform_session_token,
    issue_recovery_code,
    issue_setup_token,
    verify_platform_csrf_token,
    verify_platform_session_token,
    verify_recovery_code,
    verify_setup_token,
)
from .totp import (
    TOTP_AAD_PURPOSE,
    TOTP_ALGORITHM,
    TOTP_DIGITS,
    TOTP_PERIOD_SECONDS,
    TOTP_PURPOSE,
    TOTP_SECRET_REVISION,
    TOTP_SEED_BYTES,
    IssuedTotpSeed,
    canonical_totp_aad,
    decrypt_totp_seed,
    encrypt_totp_seed,
    find_accepted_totp_step,
    generate_totp_code,
    generate_totp_seed,
    totp_time_step,
)
from .username import (
    PLATFORM_USERNAME_CANONICALIZATION_VERSION,
    PlatformUsernameError,
    canonicalize_platform_username,
)

__all__ = [
    "PLATFORM_TOKEN_DIGEST_BYTES",
    "PLATFORM_TOKEN_ENTROPY_BITS",
    "PLATFORM_TOKEN_ENTROPY_BYTES",
    "PLATFORM_USERNAME_CANONICALIZATION_VERSION",
    "TOTP_AAD_PURPOSE",
    "TOTP_ALGORITHM",
    "TOTP_DIGITS",
    "TOTP_PERIOD_SECONDS",
    "TOTP_PURPOSE",
    "TOTP_SECRET_REVISION",
    "TOTP_SEED_BYTES",
    "IssuedPlatformAdminSession",
    "IssuedPlatformToken",
    "IssuedRecoveryCodeBatch",
    "IssuedSetupChallenge",
    "IssuedTotpSeed",
    "ConsumedSetupAuthority",
    "PlatformAdminSessionService",
    "PlatformAdminDisableResult",
    "PlatformAdminStepUpService",
    "PlatformAdminLoginService",
    "PlatformAdminHostService",
    "PlatformAdminCliApplication",
    "PlatformAdminRateLimiter",
    "PlatformAuthRateLimiter",
    "PlatformAdminSetupService",
    "PlatformAuthSession",
    "PlatformCredentialError",
    "PlatformCurrentFactorService",
    "PlatformCsrfAuthenticationError",
    "PlatformFactorRejected",
    "PlatformHostOperationRejected",
    "PlatformLoginAuditEvent",
    "PlatformLoginAuditRecorder",
    "PlatformLoginPolicy",
    "PlatformLoginRejected",
    "PlatformPasswordError",
    "PlatformPasswordHash",
    "PlatformPasswordHasher",
    "PlatformRecoveryCodeService",
    "PlatformRateLimitBlocked",
    "PlatformRateLimitPolicy",
    "PlatformRateLimitRule",
    "PlatformRateLimitSubjects",
    "PlatformRevokeAllResult",
    "PlatformSessionAuthenticationError",
    "PlatformSessionIssueError",
    "PlatformSessionTargetUnavailable",
    "PlatformStepUpAuditEvent",
    "PlatformStepUpAuditRecorder",
    "PlatformStepUpRejected",
    "PlatformTotpService",
    "PlatformUsernameError",
    "SetupChallengeResult",
    "SqlAlchemyPlatformLoginAuditRecorder",
    "SqlAlchemyPlatformStepUpAuditRecorder",
    "VerifiedPlatformFactor",
    "activate_admin_if_ready",
    "canonical_totp_aad",
    "canonicalize_platform_username",
    "decrypt_totp_seed",
    "digest_platform_csrf_token",
    "digest_platform_session_token",
    "digest_recovery_code",
    "digest_setup_token",
    "encrypt_totp_seed",
    "find_accepted_totp_step",
    "generate_totp_code",
    "generate_totp_seed",
    "issue_platform_csrf_token",
    "issue_platform_session_token",
    "issue_recovery_code",
    "issue_setup_token",
    "totp_time_step",
    "verify_platform_csrf_token",
    "verify_platform_session_token",
    "verify_recovery_code",
    "verify_setup_token",
]
