"""添加验货记录表和扩展租赁表

Revision ID: 0670a790bdd7
Revises: 501259f48019
Create Date: 2026-01-04 21:41:18.483827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0670a790bdd7'
down_revision = '501259f48019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    table_names = set(inspector.get_table_names())
    if 'rental_accessories' in table_names:
        op.drop_table('rental_accessories')
    with op.batch_alter_table('device_models', schema=None) as batch_op:
        batch_op.alter_column('device_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='设备/附件价值',
               existing_comment='设备价值',
               existing_nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('online', 'offline', collation='utf8mb4_general_ci'),
               comment='设备状态',
               existing_nullable=True,
               existing_server_default=sa.text("'online'"))

    rental_columns = {
        column['name'] for column in inspector.get_columns('rentals')
    }
    rental_indexes = {
        index['name'] for index in inspector.get_indexes('rentals')
    }
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('express_type_id',
               existing_type=mysql.INTEGER(),
               comment='顺丰快递类型ID (1=特快,2=标快,263=半日达)',
               existing_comment='顺丰快递类型ID (1=特快,2=标快,6=半日达)',
               existing_nullable=True)
        batch_op.alter_column('includes_handle',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否包含手柄（配套附件）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('includes_lens_mount',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否包含镜头支架（配套附件）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        for index_name in (
            'idx_rental_scheduled_shipping',
            'idx_rentals_includes_handle',
            'idx_rentals_includes_lens_mount',
        ):
            if index_name in rental_indexes:
                batch_op.drop_index(batch_op.f(index_name))
        # T006: 添加 photo_transfer 字段
        if 'photo_transfer' not in rental_columns:
            batch_op.add_column(sa.Column('photo_transfer', sa.Boolean(), nullable=False, server_default='0', comment='是否代传照片'))

    # T007: 创建 inspection_record 表
    if 'inspection_record' not in table_names:
        op.create_table(
            'inspection_record',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('rental_id', sa.Integer(), nullable=False),
            sa.Column('device_id', sa.Integer(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False, comment='验货状态: normal=验机正常, abnormal=验机异常'),
            sa.Column('inspector_user_id', sa.Integer(), nullable=True, comment='验货人员ID（预留）'),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
            sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
            sa.PrimaryKeyConstraint('id'),
            mysql_collate='utf8mb4_general_ci',
            mysql_default_charset='utf8mb4',
            mysql_engine='InnoDB'
        )
        inspection_record_indexes = set()
    else:
        inspection_record_indexes = {
            index['name']
            for index in sa.inspect(connection).get_indexes('inspection_record')
        }
    # T009: 为 inspection_record 创建索引
    for index_name, columns in (
        ('ix_inspection_record_device_id', ['device_id']),
        ('ix_inspection_record_rental_id', ['rental_id']),
        ('ix_inspection_record_status', ['status']),
        ('ix_inspection_record_created_at', ['created_at']),
    ):
        if index_name not in inspection_record_indexes:
            op.create_index(
                op.f(index_name),
                'inspection_record',
                columns,
                unique=False,
            )

    # T008: 创建 inspection_check_item 表
    if 'inspection_check_item' not in table_names:
        op.create_table(
            'inspection_check_item',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('inspection_record_id', sa.Integer(), nullable=False),
            sa.Column('item_name', sa.String(length=100), nullable=False, comment='检查项名称'),
            sa.Column('is_checked', sa.Boolean(), nullable=False, server_default='0', comment='是否已勾选'),
            sa.Column('item_order', sa.Integer(), nullable=False, server_default='0', comment='显示顺序'),
            sa.ForeignKeyConstraint(['inspection_record_id'], ['inspection_record.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            mysql_collate='utf8mb4_general_ci',
            mysql_default_charset='utf8mb4',
            mysql_engine='InnoDB'
        )
        inspection_item_indexes = set()
    else:
        inspection_item_indexes = {
            index['name']
            for index in sa.inspect(connection).get_indexes(
                'inspection_check_item'
            )
        }
    # T009: 为 inspection_check_item 创建索引
    inspection_item_index = 'ix_inspection_check_item_inspection_record_id'
    if inspection_item_index not in inspection_item_indexes:
        op.create_index(
            op.f(inspection_item_index),
            'inspection_check_item',
            ['inspection_record_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 inspection_check_item 表
    op.drop_index(op.f('ix_inspection_check_item_inspection_record_id'), table_name='inspection_check_item')
    op.drop_table('inspection_check_item')
    
    # 删除 inspection_record 表
    op.drop_index(op.f('ix_inspection_record_created_at'), table_name='inspection_record')
    op.drop_index(op.f('ix_inspection_record_status'), table_name='inspection_record')
    op.drop_index(op.f('ix_inspection_record_rental_id'), table_name='inspection_record')
    op.drop_index(op.f('ix_inspection_record_device_id'), table_name='inspection_record')
    op.drop_table('inspection_record')
    
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        # 删除 photo_transfer 字段
        batch_op.drop_column('photo_transfer')
        batch_op.create_index(batch_op.f('idx_rentals_includes_lens_mount'), ['includes_lens_mount'], unique=False)
        batch_op.create_index(batch_op.f('idx_rentals_includes_handle'), ['includes_handle'], unique=False)
        batch_op.create_index(batch_op.f('idx_rental_scheduled_shipping'), ['status', 'scheduled_ship_time'], unique=False)
        batch_op.alter_column('includes_lens_mount',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否包含镜头支架（配套附件）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('includes_handle',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否包含手柄（配套附件）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('express_type_id',
               existing_type=mysql.INTEGER(),
               comment='顺丰快递类型ID (1=特快,2=标快,6=半日达)',
               existing_comment='顺丰快递类型ID (1=特快,2=标快,263=半日达)',
               existing_nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('online', 'offline', collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='设备状态',
               existing_nullable=True,
               existing_server_default=sa.text("'online'"))

    with op.batch_alter_table('device_models', schema=None) as batch_op:
        batch_op.alter_column('device_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='设备价值',
               existing_comment='设备/附件价值',
               existing_nullable=True)

    op.create_table('rental_accessories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('rental_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='租赁ID'),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='附件设备ID'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('rental_accessories_ibfk_1')),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name=op.f('rental_accessories_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
