"""Add rental_statistics table

Revision ID: a514ad030209
Revises: dfcb9246b5f4
Create Date: 2025-10-11 20:21:53.161612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a514ad030209'
down_revision = 'dfcb9246b5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='统计ID'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='统计周期开始日期'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='统计周期结束日期'),
    sa.Column('total_rentals', sa.Integer(), nullable=False, comment='订单总数'),
    sa.Column('total_rent', sa.Numeric(precision=10, scale=2), nullable=False, comment='订单总租金'),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='订单总收入价值'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_statistics_stat_date'), ['stat_date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_statistics_stat_date'))

    op.drop_table('rental_statistics')
    # ### end Alembic commands ###
