"""Initial migration

Revision ID: bff12792e76a
Revises: 
Create Date: 2025-09-10 15:04:12.498249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff12792e76a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_accessories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('rental_id', sa.Integer(), nullable=False, comment='租赁ID'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='附件设备ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=False, comment='设备型号',default='x200u'))
        batch_op.add_column(sa.Column('is_accessory', sa.Boolean(), nullable=True, comment='是否为附件',default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('is_accessory')
        batch_op.drop_column('model')

    op.drop_table('rental_accessories')
    # ### end Alembic commands ###
