"""SaaS Core registration and redemption primitives."""

from .codes import (
    CROCKFORD_BASE32_ALPHABET,
    REDEMPTION_CODE_ENTROPY_BITS,
    REDEMPTION_CODE_LENGTH,
    CanonicalRedemptionCode,
    InvalidRedemptionCodeError,
    RedemptionCodeError,
    canonicalize_redemption_code,
    generate_redemption_code,
    redemption_code_lookup_hash,
)
from .envelope import (
    REDEMPTION_CODE_SECRET_PURPOSE,
    RedemptionCodeSecretContext,
    decrypt_redemption_code,
    encrypt_redemption_code,
)
from .management_service import (
    REDEMPTION_CODE_STATUSES,
    RedemptionCodeListItem,
    RedemptionCodeManagementError,
    RedemptionCodeManagementService,
    RedemptionCodeNotFound,
    RedemptionCodePage,
    RedemptionCodeRevisionConflict,
    RedemptionCodeRevocation,
    RevealedRedemptionCode,
)
from .state import (
    RedemptionCodeState,
    RedemptionCodeStateError,
    RedemptionCodeStatus,
    expire_if_due,
    redeem_for_renewal,
    redeem_reserved_registration,
    reserve_for_registration,
    revoke_after_host_restore,
)
from .service import (
    GeneratedRedemptionBatch,
    IssuedRedemptionCode,
    RedemptionBatchConflictError,
    RedemptionBatchError,
    RedemptionCodePreview,
    RedemptionCodeService,
    RedemptionGenerationDenied,
)

__all__ = [
    "CROCKFORD_BASE32_ALPHABET",
    "REDEMPTION_CODE_ENTROPY_BITS",
    "REDEMPTION_CODE_LENGTH",
    "REDEMPTION_CODE_SECRET_PURPOSE",
    "REDEMPTION_CODE_STATUSES",
    "CanonicalRedemptionCode",
    "GeneratedRedemptionBatch",
    "InvalidRedemptionCodeError",
    "IssuedRedemptionCode",
    "RedemptionBatchConflictError",
    "RedemptionBatchError",
    "RedemptionCodePreview",
    "RedemptionCodeService",
    "RedemptionCodeSecretContext",
    "RedemptionCodeState",
    "RedemptionCodeStateError",
    "RedemptionCodeStatus",
    "RedemptionCodeError",
    "RedemptionCodeListItem",
    "RedemptionCodeManagementError",
    "RedemptionCodeManagementService",
    "RedemptionCodeNotFound",
    "RedemptionCodePage",
    "RedemptionGenerationDenied",
    "RedemptionCodeRevisionConflict",
    "RedemptionCodeRevocation",
    "RevealedRedemptionCode",
    "canonicalize_redemption_code",
    "decrypt_redemption_code",
    "encrypt_redemption_code",
    "expire_if_due",
    "generate_redemption_code",
    "redeem_for_renewal",
    "redeem_reserved_registration",
    "redemption_code_lookup_hash",
    "reserve_for_registration",
    "revoke_after_host_restore",
]
