"""Privacy-safe SaaS operational state primitives."""

from .backup_signals import (
    BackupFreshnessSignalAdapter,
    BackupFreshnessSignalUpdates,
)
from .health import (
    HealthEndpointResult,
    HealthEndpointService,
    HealthTransactionRequired,
    HostRecoveryMarker,
    HostRecoveryMarkerMode,
)
from .flask_health import (
    BoundedHealthAdmissionGate,
    create_health_blueprint,
    health_response,
)
from .marker_file import (
    HostRecoveryMarkerLoadError,
    MARKER_FORMAT_VERSION,
    MAX_MARKER_BYTES,
    load_host_recovery_marker,
)
from .evaluator import (
    OperationalFreshnessEvaluator,
    OperationalFreshnessResult,
)
from .queue_signals import (
    QUEUE_TERMINAL_FAILURE_STATES,
    QueueOperationalPolicy,
    QueueOperationalSignalAdapter,
    QueueOperationalSnapshot,
)
from .service import (
    ALERT_FINGERPRINT_VERSION,
    AlertLifecycleEventRef,
    AlertLifecycleKind,
    OperationalEffectiveStatus,
    OperationalEnvironment,
    OperationalInputError,
    OperationalObservationConflictError,
    OperationalObservationStatus,
    OperationalPolicyConflictError,
    OperationalPolicyError,
    OperationalPolicyRegistry,
    OperationalResultClass,
    OperationalSignalKey,
    OperationalSignalNotFoundError,
    OperationalSignalPolicy,
    OperationalSignalService,
    OperationalSignalSnapshot,
    OperationalSignalUpdate,
    OperationalStateError,
    OperationalStateIntegrityError,
    OperationalTransactionRequiredError,
)

__all__ = [
    "ALERT_FINGERPRINT_VERSION",
    "AlertLifecycleEventRef",
    "AlertLifecycleKind",
    "BackupFreshnessSignalAdapter",
    "BackupFreshnessSignalUpdates",
    "BoundedHealthAdmissionGate",
    "HealthEndpointResult",
    "HealthEndpointService",
    "HealthTransactionRequired",
    "HostRecoveryMarker",
    "HostRecoveryMarkerLoadError",
    "HostRecoveryMarkerMode",
    "MARKER_FORMAT_VERSION",
    "MAX_MARKER_BYTES",
    "create_health_blueprint",
    "health_response",
    "load_host_recovery_marker",
    "OperationalEffectiveStatus",
    "OperationalFreshnessEvaluator",
    "OperationalFreshnessResult",
    "OperationalEnvironment",
    "OperationalInputError",
    "OperationalObservationConflictError",
    "OperationalObservationStatus",
    "OperationalPolicyConflictError",
    "OperationalPolicyError",
    "OperationalPolicyRegistry",
    "OperationalResultClass",
    "OperationalSignalKey",
    "OperationalSignalNotFoundError",
    "OperationalSignalPolicy",
    "OperationalSignalService",
    "OperationalSignalSnapshot",
    "OperationalSignalUpdate",
    "OperationalStateError",
    "OperationalStateIntegrityError",
    "OperationalTransactionRequiredError",
    "QUEUE_TERMINAL_FAILURE_STATES",
    "QueueOperationalPolicy",
    "QueueOperationalSignalAdapter",
    "QueueOperationalSnapshot",
]
