"""Non-secret lifecycle registry for versioned platform root keys."""

from __future__ import annotations

from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Mapped, mapped_column

from .base import ControlBase


SHA256_DIGEST_TYPE = sa.LargeBinary(32).with_variant(mysql.BINARY(32), "mysql")


class PlatformRootKeyVersion(ControlBase):
    """One non-secret platform root-key version registry row.

    Key material and filesystem locations deliberately have no representation
    in this model.  ``active_slot`` is generated by the database solely to make
    the single-active invariant safe under concurrent writers.
    """

    __tablename__ = "platform_root_key_versions"
    __table_args__ = (
        sa.UniqueConstraint(
            "fingerprint_sha256",
            name="uq_root_key_versions_fingerprint",
        ),
        sa.UniqueConstraint(
            "active_slot",
            name="uq_root_key_versions_active_slot",
        ),
        sa.CheckConstraint("version >= 1", name="version_positive"),
        sa.CheckConstraint(
            "length(fingerprint_sha256) = 32",
            name="fingerprint_length",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'legacy', 'retired')",
            name="status_valid",
        ),
        sa.CheckConstraint(
            "((status = 'retired' AND retired_at IS NOT NULL) OR "
            "(status IN ('active', 'legacy') AND retired_at IS NULL))",
            name="retired_at_matches_status",
        ),
    )

    version: Mapped[int] = mapped_column(
        sa.BigInteger,
        primary_key=True,
        autoincrement=False,
    )
    fingerprint_sha256: Mapped[bytes] = mapped_column(
        SHA256_DIGEST_TYPE, nullable=False
    )
    status: Mapped[str] = mapped_column(sa.String(16), nullable=False)
    active_slot: Mapped[int | None] = mapped_column(
        sa.SmallInteger,
        sa.Computed(
            "CASE WHEN status = 'active' THEN 1 ELSE NULL END",
            persisted=True,
        ),
        nullable=True,
    )
    activated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    retired_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )


__all__ = ["PlatformRootKeyVersion"]
